spring:
  data:
    mongodb:
      uri: mongodb://movie-service-mongodb:27017/movie-service
management:
  endpoints:
    web:
      exposure:
        include: health
integration:
  tmdb-api:
    url: https://api.themoviedb.org/3
    url-image: https://image.tmdb.org/t/p/w500
    key: eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxM2Y0MWUwNTdlNDg4MTljZjg3OWY3YzQ4YTNmYjQ1OSIsIm5iZiI6MTczMTg3MzMyOS43OTI4MjksInN1YiI6IjY2ZjgzMjA5NjIxZTg2MTZiNDVmM2VmYiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.mlsLhOfl4X5E_JDn-Oy-OoyQcyEHMbC_zzbfr-QrWKs
    retry:
      max-attempts: 3
      delay: 1000
  s3:
    endpoint: http://movie-service-minio:9000
    access-key: user
    secret-key: password
    region: us-east-1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
scheduled:
  task:
    update-db: "0 0 3 * * ?"
